#---
- name: Install FreeIPA packages and dependencies
  package: name={{ item }} state=present
  with_items: "{{ ipaserver_packages }}"

- name: Install Python module dependencies (pexpect)
  pip:
    name: pexpect
    state: present

- name: Hard set the hostname to the FQDN
  hostname: name={{ ansible_fqdn }}

- name: Remove 127.0.0.1 -> FQDN hosts entry
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1\s+{{ ansible_fqdn }}'
    state: absent

- name: Add private IP -> FQDN hosts entry
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ ansible_fqdn }}"
    line: "{{ ipaserver_ip_address }}   {{ ansible_fqdn }} {{ ansible_hostname }}"

# todo: move to a lib
# todo: change creates condition to ipa query command -> registered var
- name: Run the installer
  action: command
    {{ ipaserver_base_command }}
    --realm {{ ipaserver_realm }}
    --domain {{ ipaserver_domain }}
    -a {{ ipaserver_admin_password }}
    -p {{ ipaserver_dir_admin_password }}
    --hostname={{ ansible_fqdn }}
    --ip-address={{ ipaserver_ip_address }}
    {{ '--idstart=%s' % ipaserver_idstart if ipaserver_idstart | default(False) else '' }}
    {{ '--idmax=%s' % ipaserver_idmax if ipaserver_idmax | default(False) else '' }}
    {{ '--forwarder=%s' % ipaserver_dns_forwarder
       if ipaserver_dns_forwarder | default(False) else '--no-forwarders' }}
    {{ '--mkhomedir' if ipaserver_mkhomedir | default(True) else '' }}
    {{ '--setup-dns' if ipaserver_setup_dns | default(True) else '' }}
    {{ '--ssh-trust-dns' if ipaserver_ssh_trust_dns | default(True) else '' }}
    {{ '' if ipaserver_hbac_allow | default(True) else '--no_hbac_allow' }}
    {{ '' if ipaserver_setup_ntp | default(True) else '--no-ntp' }}
    {{ '' if ipaserver_configure_ssh | default(True) else '--no-ssh' }}
    {{ '' if ipaserver_configure_sshd | default(True) else '--no-sshd' }}
    {{ '' if ipaserver_ui_redirect | default(True) else '--no-ui-redirect' }}
        --no-host-dns
    creates=/etc/ipa/default.conf

- name: Override DNS server(s) - Add DNS server to ifcfg
  lineinfile:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
    regexp: DNS1=
    line: "DNS1={{ ipaserver_ip_address }}"
  when: ipaserver_setup_dns

- name: Override DNS server(s) - Disable PEERDNS in ifcfg
  replace:
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}"
    regexp: PEERDNS=yes
    replace: PEERDNS=no
  when: ipaserver_setup_dns

- name: Disable DNS management in NetworkManager config
  lineinfile:
    dest: /etc/NetworkManager/NetworkManager.conf
    regexp: dns=none
    line: dns=none
    insertafter: '\[main\]'
  when: ipaserver_setup_dns

- name: Override DNS server(s) in resolv.conf
  lineinfile:
    dest: /etc/resolv.conf
    regexp: nameserver
    line: "nameserver {{ ipaserver_ip_address }}"
  when: ipaserver_setup_dns
